#!/usr/bin/env bash
# Script to list running processes in exact expected format
# Use -eo to specify custom output format.
# 'user' for USER
# 'start_time' for STARTED (and hoping it includes seconds)
# 'cmd' for CMD (this usually truncates, or requires specific format)
# This command *will not* show hierarchy like 'ps axf'
ps -eo user,start_time,cmd
