#!/usr/bin/env bash
# Lists all running processes with user, start time, and command

echo "USER STARTED CMD"
ps -eo user,lstart,cmd --no-headers | awk '{ 
    printf "%s %s:%s:%s %s\n", $1, $4, $5, $6, $8 
}'
